version: "3.5"

services:
  gptslackbot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: gptslackbot
    restart: always
    container_name: gptslackbot
    env_file:
      - ".api.env"
    ports:
      - "3000:3000"
